config/routes.rb
Rails.application.routes.draw do
  get 'check_ins/new'
  get 'check_ins/create'
  get 'spots/index'
  devise_for :skaters 
  get "skaters/:id", to: "pages#profile"
  root to: 'spots#index'
  resources :spots do
    resources :check_ins, only: :create
    member do
      post "toggle_favorite", to: "spots#toggle_favorite"
    end
  end
  resources :skaters
  resources :tags, only: :destroy
  post "spots/:id", to: "tags#create", as: "new_tag"
  post "skaters/:id", to: "pages#toggle_favorite", as: "toggle_favorite_skater"
  get "/feed", to: "pages#feed", as: "feed"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
  belongs_to :skater
  belongs_to :spot
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/skater.rb
class Skater < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :spots
  has_many :tags
  has_many :check_ins
  # validates :username, presence: true, uniqueness: true
  acts_as_favoritor
  acts_as_favoritable
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :skater
  has_many :tags, dependent: :destroy
  has_many :check_ins, dependent: :destroy
  has_many_attached :photos
  validates :name, presence: true, length: { in: 3..30 }
  geocoded_by :location
  after_validation :add_coordinates, if: :will_save_change_to_location?
  validates :photos, presence: true
  acts_as_favoritable

  private

  def add_coordinates
    self.geocode
    if !latitude && location
      location = location.split(",").slice(1..-1).join
      self.save
      self.geocode
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :skater
  belongs_to :spot
  validates :url, presence: true
  validates :caption, presence: true, length: { in: 1..40 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_skater!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/check_ins_controller.rb
class CheckInsController < ApplicationController
  def create
    @check_in = CheckIn.new
    @spot = Spot.find(params[:spot_id])
    @check_in.skater = current_skater
    @check_in.spot_id = params[:spot_id]
    @check_in.save
    redirect_to @spot
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_skater!, only: :home
  def home
  end
  
  def profile
   @skater = Skater.find(params[:id])
   @current_skater = current_skater
   if !params[:ajax]
    cookies["followers"] = @current_skater.favoritors.count
   end
  end

  def toggle_favorite
    @skater = Skater.find(params[:id])
    current_skater.favorited?(@skater) ? current_skater.unfavorite(@skater) : current_skater.favorite(@skater)
  end
  
  def feed
    @current_skater = current_skater
    @activity = []
    @current_skater.favorited_skaters.each do |skater|
      skater.check_ins.each do |c|
      @activity << c
      end
    skater.favorites_by_type('Spot').each do |fs|
      @activity << fs
    end
      @activity << Tag.find_by_skater_id(skater.id)
      @activity = @activity.compact.sort_by { |a| a.created_at }.reverse!
    end

    if !params[:ajax]
      cookies["activity"] = @activity.count
    end
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
    skip_before_action :authenticate_skater!, only: [:show, :index]
  def index

    if params[:filters].present?
      filters = {
        stairset: (params[:filters][:stairset] == "1"),
        ledge: (params[:filters][:ledge] == "1"),
        cover: (params[:filters][:cover] == "1"),
        flatground: (params[:filters][:flatground] == "1")
      }
      if params[:filters][:center]
        @map_center = params[:filters][:center]
      end
      
      @spots = Spot.where(filters.select { |_k, v| v })
    else
      @spots =  Spot.all
    end

    @markers = @spots.geocoded.map do |spot|
      {
        lat: spot.latitude,
        lng: spot.longitude,
        info_window: render_to_string(partial: "info_window", locals: { spot: spot })
      }
    end
    
  end

  def show
    @current_skater = current_skater
    @spot = Spot.find(params[:id])
    @tag = Tag.new
    @tags = @spot.tags.all.reverse
    if @current_skater
      @checked_in = CheckIn.all
      @result = @checked_in.select {|c| c.skater_id == current_skater.id && (Time.now - c.created_at) < 2.hours && c.spot_id == @spot.id }
      @atm = @checked_in.select { |c| (Time.now - c.created_at) < 2.hours && c.spot_id == @spot.id }
    end
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(spot_params)
    @spot.skater = current_skater
    if @spot.save
      redirect_to @spot
    else
      render :new
    end
  end

  def edit
    @spot = Spot.find(params[:id])
  end

  def update
    @spot = Spot.find(params[:id])
    if @spot.update(spot_params)
      redirect_to spot_path(@spot)
    else
      render :edit
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
    redirect_to root_path
  end

  def toggle_favorite
    @spot = Spot.find(params[:id])
    current_skater.favorited?(@spot) ? current_skater.unfavorite(@spot) : current_skater.favorite(@spot)
  end

  private

  def spot_params
    params.require(:spot).permit(:name, :description, :stairset, :security, :location, :cover, :ledge, :flatground, photos: [])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
    @tag = Tag.new(tag_params)
    @spot = Spot.find(params[:id])
    @tag.spot = @spot
    @current_skater = current_skater
    @tag.skater_id = @current_skater.id
    if @tag.save
      redirect_to spot_path(@spot)
    else
      render "spots/show"
    end
  end

  def destroy
    @tag = Tag.find(params["tag_id"].to_i)
    @spot = Spot.find(params["spot_id"].to_i)
    @tag.destroy
    redirect_to @spot
  end

  private

  def tag_params
    params.require(:tag).permit(:url, :caption)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :skater
  end

  def resource
    @resource ||= Skater.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:skater]
  end

  def resource_class
    devise_mapping.to
  end
end

app/helpers/meta_tag_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spotter | Local grinds</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="description" content="<%= meta_description %>">
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <link rel="shortcut icon" type="image/jpg" href="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/285/skateboard_1f6f9.png"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= render 'shared/nav_bottom' %>
  </body>
</html>

app/views/pages/feed.html.erb
<h6 class='feed-title'>feed <i class="bi bi-rss blink_me "></i></h6>

<div class="feed">
  <% @activity.each do |instance| %>
    <div class="feed-card">
      <% if (instance.class.name == "CheckIn" || instance.class.name == "Spot") && instance.skater_id == 15 %>
        <img class='feed-avatar' src="https://theboardr.com/_next/image?url=https%3A%2F%2Ftheboardr.blob.core.windows.net%2Fheadshots%2F923_900.jpg&w=768&q=75" alt="">
      <% end %>
      <% if (instance.class.name == "CheckIn" || instance.class.name == "Spot") && instance.skater_id == 14 %>
        <img class='feed-avatar' src="https://www.liveabout.com/thmb/3_ekV83ptU1AP_CzmwLG2Dnb7AE=/768x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/aol-s-build-speaker-series-present---we-are-blood--484618744-599ce0ed054ad9001128c0ba.jpg" alt="">
      <% end %>
      <% if (instance.class.name == "CheckIn" || instance.class.name == "Spot") && instance.skater_id == 16 %>
        <img class='feed-avatar' src="https://theboardr.com/_next/image?url=https%3A%2F%2Ftheboardr.blob.core.windows.net%2Fheadshots%2F2685_900.jpg&w=768&q=75" alt="">
      <% end %>
      
      <% if instance.class.name == "Favorite" && instance.favoritor_id == 15 %>
        <img class='feed-avatar' src="https://theboardr.com/_next/image?url=https%3A%2F%2Ftheboardr.blob.core.windows.net%2Fheadshots%2F923_900.jpg&w=768&q=75" alt="">
      <% end %>
      <% if instance.class.name == "Favorite" && instance.favoritor_id == 14 %>
        <img class='feed-avatar' src="https://www.liveabout.com/thmb/3_ekV83ptU1AP_CzmwLG2Dnb7AE=/768x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/aol-s-build-speaker-series-present---we-are-blood--484618744-599ce0ed054ad9001128c0ba.jpg" alt="">
      <% end %>
      <% if instance.class.name == "Favorite" && instance.favoritor_id == 16 %>
        <img class='feed-avatar' src="https://theboardr.com/_next/image?url=https%3A%2F%2Ftheboardr.blob.core.windows.net%2Fheadshots%2F2685_900.jpg&w=768&q=75" alt="">
      <% end %>
      <% if instance.class.name == "CheckIn" %>
        <% @spot = Spot.find(instance.spot_id) %>
        <% @skater = Skater.find(instance.skater_id) %>
        <% @time = instance.created_at %>
        <p><%= link_to skater_path(@skater) do %>
          <strong><%= @skater.username %></strong>
        <% end %> dropped in to <%= link_to spot_path(@spot) do %>
          <strong><%= @spot.name %></strong>
        <% end %>
        <%= time_ago_in_words(@time) %> ago</p>
      <% elsif instance.class.name == "Favorite" %>
        <% @spot = Spot.find(instance.favoritable_id) %>
        <% @skater = Skater.find(instance.favoritor_id) %>
        <% @time = instance.created_at %>
        <p><%= link_to skater_path(@skater) do %>
          <strong><%= @skater.username %></strong>
        <% end %> liked <%= link_to spot_path(@spot) do %>
          <strong><%= @spot.name %></strong>
        <% end %> 
        <%= time_ago_in_words(@time) %> ago</p>
      <% else %>
        <% @spot = Spot.find(instance.spot_id) %>
        <% @skater = Skater.find(instance.skater_id) %>
        <% @time = instance.created_at %>
        <p><%= link_to skater_path(@skater) do %>
          <strong><%= @skater.username %></strong>
        <% end %> tagged <%= link_to spot_path(@spot) do %>
          <strong><%= @spot.name %></strong>
        <% end %>
        <%= time_ago_in_words(@time) %> ago</p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<%= link_to "New spot", new_spot_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_nav_bottom.html.erb
<footer id="spt-footer" class="navbar fixed-bottom navbar-light">


  <div class="geocoder" id="geocoder" style="width: 60%;"></div>


  <div class="btn-group dropup">
  <button type="button" class="btn-normal btn-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Menu
  </button>
  <div class="dropdown-menu dropdown-menu-right">
    <div class="footer-menu">
      <a class="dropdown-item" href="/"><i class="fas fa-map-marked-alt"></i> Spot Map</a>
      <a class="dropdown-item" href="/feed"><i class="fas fa-bars"></i> Feed</a>
      <a class="dropdown-item" href="/spots/new"><i class="fas fa-plus"></i> New Spot</a>
      <div id="notif" class="d-none"></div>
    </div>
  </div>
</div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" data-id="<%= current_skater.id if skater_signed_in? %>">
  <a id='spotter-logo' class="navbar-brand" href="/">🛹 Spotter</a>
  <%# removed this class from here navbar-collapse %>
  <div id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">

        <%# CHECK THE USER/SKATER %>
        <% if current_skater %>


        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://theboardr.blob.core.windows.net/headshots/25272_900.jpg" />

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <p class="dropdown-item disabled user"><%= current_skater.username %></p>
            <%= link_to "Profile", skater_path(current_skater), class: "dropdown-item" %>
            <%= link_to "Sign Out", destroy_skater_session_path, method: :delete, class: "dropdown-item" %>
          </div>
          <div class='online-badge'></div>
        <% else %>

        <a class="nav-link text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Login
        </a>
        <div class="dropdown-menu dropdown-menu-right">

          <%# THIS GOES TO THE APPLICATION HELPER.RB %>
          <%# REMOVE LOG IN HEADER %>
          <%# <h2>Log in</h2> %>
          <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="form-inputs m-3">
              <%= f.input :email,
                required: false,
                autofocus: true,
                label: false,
                input_html: { autocomplete: "email" } %>
              <%= f.input :password,
                required: false,
                label: false,
                input_html: { autocomplete: "current-password" } %>
              <div class="login-buttons">
                <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
                <div class="form-actions">
                  <%= f.button :submit, "Log in", class: "btn-cta" %>
                </div>
              </div>
              
            </div>
            
          <% end %>


        <%# END OF THE IF STATEMENT %>
        <% end %>

        </div>
      </li>
    </ul>
  </div>
</nav>
<a href='/skaters/<%= current_skater.id if current_skater %>'><div class="follower_notif shadow d-none"></div></a>

app/views/spots/_info_window.html.erb
<a href='/spots/<%=spot.id%>'>
  <h4><%= spot.name %></h4>
</a>

<%# TOOK OUT THE LOCATION %>
<%# <p><%= spot.location ADD P END! %>

<div class="popup-icons">
    <% if spot.cover %>
    <p><i class="fas fa-umbrella"></i></p>
    <%end%>
    <% if spot.flatground %>
    <p><i class="fas fa-grip-lines"></i></p>
    <%end%>
    <% if spot.stairset %>
    <p><i class="bi bi-bar-chart-steps"></i></p>
    <%end%>
    <% if spot.ledge %>
    <p><i class="fas fa-tenge"></i></p>
    <%end%>
    <%# <p><i class="fas fa-hand-paper"></i> <%= spot.security.downcase  ADD P AND PE ENDING TAGS%>
  </div>

app/views/spots/index.html.erb
<script>
  let vh = window.innerHeight * 0.01;
  document.documentElement.style.setProperty('--vh', `${vh}px`);
</script>
<style>
@media only screen and (min-width: 414px) {
  #map {
  min-width: 414px;
  min-height: 500px;
}
}

#map {
  width: 100%;
  height: calc(var(--vh, 1vh) * 100 - 33vh); 
  <%# 248.63px); %>
}

.mapboxgl-canvas {
  width: 100vw !important;
}

</style>
<div>
  <div id="map"
    
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    data-center=<%= @map_center ? @map_center : ""  %> >
  </div>

  <%= simple_form_for :filters, url: spots_path, method: :get do |f| %>

  <div class="filter-container">


    <div class="filter-options">
      <%= f.input :stairset, as: :boolean, label: 'Stairset <p><i class="bi bi-bar-chart-steps"></i></p>'.html_safe, input_html: { style: "display: none", class: 'filter-input', checked: params.dig(:filters, :stairset) == "1" }, label_html: { class: "filter-options" } %> 

      <%= f.input :ledge, as: :boolean, label: 'Ledge <p><i class="fas fa-tenge"></i></p>'.html_safe, input_html: { style: "display: none", class: 'filter-input', checked: params.dig(:filters, :ledge) == "1" }, label_html: { class: "filter-options" } %>

      <%= f.input :cover, as: :boolean, label: 'Cover <p><i class="fas fa-umbrella"></i></p>'.html_safe, input_html: { style: "display: none", class: 'filter-input', checked: params.dig(:filters, :cover) == "1" }, label_html: { class: "filter-options" } %>

      <%= f.input :flatground, as: :boolean, label: 'Flat <p><i class="fas fa-grip-lines"></i></p>'.html_safe, input_html: { style: "display: none", class: 'filter-input', checked: params.dig(:filters, :flatground) == "1" }, label_html: { class: "filter-options" } %>

      <%= f.input :center, as: :hidden, input_html: { id: "hidden-center", value: [] } %>
    </div>

    <%= f.submit "Filter", class: "btn-filter" %>
    </div>
  <% end %>
</div>

app/views/spots/show.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '517239189416893',
      xfbml      : true,
      version    : 'v11.0'
    });
    FB.AppEvents.logPageView();
  };
  
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
<% if @spot.photos.first != nil %>
<div class='spot-main-banner shadow-lg'  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @spot.photos.first.key %>')">
<% else %>
<div class='spot-main-banner shadow-lg'  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://www.skateparks.co.uk/wp-content/uploads/2018/11/Acton-Skatepark-1.jpeg')">
  <% end %>
  <h5 class='spot-name'> <%= @spot.name %></h5>
  <a href="https://www.google.com/maps/place/<%=@spot.location %>/" target='_blank'>
    <p class='spot-address'><i class="fas fa-map-marked-alt"></i> <%= @spot.location.split(",").slice(0..1).join(",") %></p>
  </a>
  <% if current_skater %>
  <% if current_skater.favorited?(@spot) %>
  <%= link_to toggle_favorite_spot_path(@spot), remote: true, method: :post do %>
  <i class="fas fa-heart" style="color: red;"></i>
  <span class='favorite-count'><%= @spot.favoritors.count %></span>
  <% end %>
  <% else %>
  <%= link_to toggle_favorite_spot_path(@spot), remote: true, method: :post do %>
  <i class="fas fa-heart" style="color: white;"></i>
  <span class='favorite-count'><%= @spot.favoritors.count %></span>
  <% end %>
  <% end %>
  <% if @result.count == 0 %>
  <div class='spot-dropin'><%= link_to "DROP IN", spot_check_ins_path(@spot), method: :post, class: 'btn-dropin btn btn-primary' %></div>
  <% else %>
  <div class='dropped-in'>DROPPED IN</div>
  <% end %>
  <% if @current_skater %>
  <button type="button" class="btn btn-primary tag-btn" data-toggle="modal" data-target=".bs-example-modal-new">TAG</button>
  <% end %>
  <% end %>
</div>
<div class='spot-info-container'>
  <div style='width: 40px' class='spot-info-icon'>
    <% if current_skater %>
    <p><i class="fas fa-user-clock"></i> <%= @atm.count %></p>
    <% end %>
  </div>
  <div class='info-icon-container'>
    <% if @spot.cover %>
    <div class='spot-info-icon'>
      <p> <i class="fas fa-umbrella"></i></p>
    </div>
    <%end%>
    <% if @spot.flatground %>
    <div class='spot-info-icon'>
      <p><i class="fas fa-grip-lines"></i></p>
    </div>
    <%end%>
    <% if @spot.stairset %>
    <div class='spot-info-icon'>
      <p><i class="bi bi-bar-chart-steps"></i></p>
    </div>
    <%end%>
    <% if @spot.ledge %>
    <div class='spot-info-icon'>
      <p><i class="fas fa-tenge"></i></p>
    </div>
    <%end%>
    <% if @spot.security == 'High' %>
        <div class='spot-info-icon'>
      <p><i style='color:red;' class="fas fa-hand-paper"></i></p>
    </div>
    <% end %>
    <% if @spot.security == 'Medium' %>
        <div class='spot-info-icon'>
      <p><i style='color:orange;' class="fas fa-hand-paper"></i></p>
    </div>
    <% end %>
    <% if @spot.security == 'Low' %>
        <div class='spot-info-icon'>
      <p><i style='color:#239e33;' class="fas fa-hand-paper"></i></p>
    </div>
    <% end %>
  </div>
</div>
<div class='spot-description-container'>
  <h6 class='spot-description-header'><i class="fas fa-info-circle"></i> &nbsp INFO</h6>
  <p class='spot-description-body'><%= @spot.description %></p>
</div>
<div class="modal fade bs-example-modal-new" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <!-- Modal Content: begins -->
    <div class="modal-content">
      <!-- Modal Header -->
      <div class="modal-header">
        <h4 id ='tag-header'><i class="fas fa-plus"></i> Tag <%= @spot.name %></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <!-- Modal Body -->  
      <div class="modal-body">
        <div class="body-message">
          <p class='modal-message'>Got a sweet line you want to share?</p>
          <div class='mt-4 mb-2'>
            <%= simple_form_for @tag, url: new_tag_path, html: { class: "col-sm-6 offset-sm-3" } do |f| %>
            <div class='mb-2 tag-label'><i class="bi bi-link-45deg"></i> YouTube Link</div>
            <%= f.input :url, label: false %>
            <div class='mb-2 tag-label'><i class="bi bi-chat-left-quote"></i> Caption</div>
            <%= f.input :caption, label: false %>
            <%= f.button :submit, class: 'btn btn-primary create-tag-btn' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div style='margin: 10px;'>
  <% if @tags.count >= 1 %>
    <% @tags.each do |t| %>
    <div class='youtube-card' style='margin-bottom: -10px;'>
      <% @time = t.created_at %>
      <div class="">
        <div class='tag-card-head p-2'>
        <% if current_skater == t.skater %>
          <div class="card-tag-left">
            <p class='tag-caption'><%= t.caption %></p>
          </div>
          <div class="card-tag-right">
            <p class='tag-username'><%= time_ago_in_words(@time) %> AGO BY <%= t.skater.username %>        <div class="delete-tag"><%= button_to "🗑", {:controller => "tags", :action => "destroy", :spot_id => @spot.id, :tag_id => t.id }, :method=>:delete %></div></p>
            <a href="/skaters/<%= t.skater_id %>"></a>
          </div>
        <% else %>
          <div class="card-tag-left">
            <p class='tag-caption'><%= t.caption %></p>
          </div>
          <div class="card-right-tag">
            <p class='tag-username'><%= time_ago_in_words(@time) %> AGO BY <%= t.skater.username %></p>
            <a href="/skaters/<%= t.skater_id %>"></a>
          </div>
        <% end %>
        </div>
          <div class="video-card">
            <div class="urlbb"><%= t.url %></div>
            <div class="tag-photo">
            <p class="post"></p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <% else %>
    <div class="no-video-alert">
      <p>No videos uploaded. Be the first to <strong>ta<span class ="harry-word">g!</strong></span></p>
    </div>
  <% end %>
</div>
<%= javascript_pack_tag "like" %>
<script async charset="utf-8" src="https://platform.instagram.com/en_US/embeds.js" ></script>